### PR TITLE
Fixes clashes with Scalaz implicits.

### LINKED ISSUE #17: `ensuring` in ResultantMonad clashes with inbuild ensuring.
Scala already has a method called `ensuring` with the whole implicit resolution this can cause clashes.

### PR DESCRIPTION
**Pull request by stephanh**
When importing scalaz syntax implicits at the same time as the resultant
monad implicits there would be clashes.

This fixes the clashes by:
* Turning ResultantOps into a class that the companion object inherits
  from.
* Changing ResultantMonadSyntax so that the companion object mixes in
  the implicit conversion trait.
* Renaming `ensuring` to `ensure` in ResultantMonadSyntax to avoid
  clashing with the inbuilt scala `ensuring`.  This closes #17.
* Removing the `|||` in ResultantMonadSyntax to avoid clashing with the
  `|||` operator in Scalaz ChoiceOps.

### CODE REVIEW

File: core/src/main/scala/au/com/cba/omnia/omnitool/ResultantOps.scala [hunk 1]
```diff
@@ -16,27 +16,33 @@ package au.com.cba.omnia.omnitool
...
 import scalaz.syntax.monad._
 
-/** Convenient operations that you can do on the companion of a [[ResultantMonad]]. */
-final class ResultantOps[O, M[_]](self: O)(implicit val M: ResultantMonad[M]) {
+/**
+  * Convenient operations that you can do on the companion of a [[ResultantMonad]].
+  *
+  * The companion object should extend this class to avoid clashing with Scalaz implicits.
+  */
+abstract class ResultantOps[M[_]] {
```
Comment (SamRoberts) [inline core/src/main/scala/au/com/cba/omnia/omnitool/ResultantOps.scala]: out of curiosity, why is this an abstract class rather than a trait?

File: core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala [hunk 2]
```diff
@@ -79,6 +79,7 @@ Resultant Monad should:
     x <+> y must equal(x or y)
   )
 
+<<<<<<< HEAD
```
Comment (SamRoberts) [inline core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala]: git merge conflict?

File: core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala [hunk 3]
```diff
@@ -91,8 +92,10 @@ Resultant Monad should:
     Resultant.result(x).addMessage(msg) must beResult(x.addMessage(msg))
   )
 
+=======
+>>>>>>> Fixes clashes with Scalaz implicits.
```
Comment (SamRoberts) [inline core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala]: more git merge conflict rubbish

File: core/src/main/scala/au/com/cba/omnia/omnitool/ResultantOps.scala (hunk 1 above)
Comment (stephanh) [inline core/src/main/scala/au/com/cba/omnia/omnitool/ResultantOps.scala]: No good reason. I think it is just a left over from when I was playing around with different solutions.

I have changed it to a trait.

File: core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala (hunk 2 above)
Comment (stephanh) [inline core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala]: Fixed.

File: core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala (hunk 3 above)
Comment (stephanh) [inline core/src/test/scala/au/com/cba/omnia/omnitool/test/ResultantMonadSpec.scala]: Fixed.

**Comment by SamRoberts** [comment]
:+1:

File: core/src/main/scala/au/com/cba/omnia/omnitool/ResultantMonadSyntax.scala [hunk 4]
```diff
@@ -97,11 +93,15 @@ final class ResultantMonadOps[M[_], A](val self: M[A])(implicit val M: Resultant
...
     a <- self
-    r <- during(a) ensuring after(a)
+    r <- during(a) ensure after(a)
   } yield r
 }
 
-/** Pimps a [[ResultantMonad]] to have access to the functions in [[ResultantMonadOps]]. */
+/** Pimps a [[ResultantMonad]] to have access to the functions in [[ResultantMonadOps]].
+  *
+  * The usual use of this is to mix it into the companion object to ensure the implicit resolution
```
Comment (vineethvarghese) [inline core/src/main/scala/au/com/cba/omnia/omnitool/ResultantMonadSyntax.scala]: I am not quite clear about this. Are we saying that we took this approach to ensure implicit resolution priority and this is not our usual approach?

Comment (stephanh) [inline core/src/main/scala/au/com/cba/omnia/omnitool/ResultantMonadSyntax.scala]: Yes.

There are different priorities of implicit resolution. The approach we normally take is to import an object that provides the implicit conversion. However, that creates some clashes with the scalaz implicit resolution. In order to avoid this we need to mix this trait into the companion object and then it will have a higher implicit resolution.

Comment (vineethvarghese) [inline core/src/main/scala/au/com/cba/omnia/omnitool/ResultantMonadSyntax.scala]: :+1:
